### ISSUE TITLE
Change icon for missing export function in the tree

### ISSUE THREAD

**Issue by tmontane** [lucasg/Dependencies#48] opened 2019-01-16 14:42 UTC
Hi,

Can you change the icon (add an overlay or something) in the tree view, so when an imported function is missing from a module, the module and/or dependent module will appear differently in the tree (in red or something) ? As I can see know (building from the latest source), the tree is the same and overlays are added when it's delay load or else, but no specific overlay is added for missing imported function in a module).
The grid that shows the missing exported function is fine, if I select a module the missing function is in red in that view, but the tree remains unaffected like if everything was fine.

Regards,

**Comment by lucasg** [comment] 2019-01-20 20:31
This is duplicate of https://github.com/lucasg/Dependencies/issues/47
By the way, I've added a red overlay for error modules.

**Closed by lucasg** 2019-01-20 20:31 UTC
