### ISSUE TITLE
PUA.Win64.ProcHack.B.component

### ISSUE THREAD

**Issue by zooid** [lucasg/Dependencies#94] opened 2019-11-08 16:13 UTC
Trend Micro detecting Malware (Spyware)

file - peview.exe

**Comment by lucasg** [comment] 2019-11-08 17:27
this is a duplicate of https://github.com/lucasg/Dependencies/issues/84
You can download a version without peview.exe embedded if this is an issue for you

**Closed by lucasg** 2019-11-08 17:27 UTC
