### ISSUE TITLE
When API-MS-***.dll  *files* are present, they're displayed even when not used

### ISSUE THREAD

**Issue by OfekShilon** [lucasg/Dependencies#10] opened 2018-02-08 07:40 UTC
On my PATH I have a program (TortoiseSVN) that has its own API-set DLLs.  
Here is a screenshot of Dependencies analysis of some program (windbg.exe), that shows the PATH copies of the actual DLLs, but any inspection (eg with ProcessExplorer) shows they're not actually used:
![image](https://user-images.githubusercontent.com/73080/35960847-f141e15a-0cb3-11e8-8140-5e4bdad2bdc5.png)

I suspect it is an issue with the order of simulated resolution - maybe DLLs in the executable folder are considered before the ApiSet mechanism, and the ApiSet mechanism is considered before the PATH search.

**Comment by lucasg** [comment] 2018-02-08 20:05
Thanks for the report,

I confirmed the issue with Firefox (which bundle all the min win dlls with its binaries). The ApiSet shema is barely documented and yet completely reversed this part of ntdll's loader. 

I guess it probably tries to resolve the import name as a dll before making the api set lookup in the case the regular dll search failed.

**Comment by lucasg** [comment] 2018-02-13 12:25
Your issue has recently been fixed by this commit : https://github.com/lucasg/Dependencies/commit/c56cd0280b74d77ca534743ace350a3be333787f. Before that, the Imports listview had a separate DLL path resolver that was a bit bugged. Now every DLL load is handled by an app-wide path resolver.


You can grab an updated version here : https://ci.appveyor.com/project/lucasg/dependencies/build/job/m3ft0c0pn5vc9685/artifacts

**Closed by lucasg** 2018-02-13 12:25 UTC

**Comment by OfekShilon** [comment] 2018-02-14 17:20
Great! thanks.   BTW, are you aware of dependencies.exe being blocked by windows SmartScreen?  Not sure there's much that can be done about it, but maybe there is
![clipboard01](https://user-images.githubusercontent.com/73080/36218114-0c6466da-11bc-11e8-8f49-1fe4ae38264d.png)

**Comment by lucasg** [comment] 2018-02-14 17:40
Yeah I'm aware 😢. Since the application is not signed and seldom downloaded so it triggers the ML-based detector (there is note on this in the `README.md`). 

Getting a code signing certificate  and sign all the binaries with would definitively help, but I need to shell out ~100€ for it. I hope someday of a Let's Encrypt for code signing certs.
